
function main()
    
     %Quantidade de neurônios por componentes.
     comp_1 = 500:100:900;
     comp_2 = 500:100:1400;
     comp_3 = 500:100:1900;
     comp_4 = 500:100:2400;
     comp_5 = 500:100:2900;
     comp_6 = 500:100:3400;
     
     components = {comp_1, comp_2, comp_3, comp_4, comp_5, comp_6};
     
     fwavelet = {'db2', 'db4', 'sym3', 'sym4', 'sym5'};
     type = 'fwavelet';
    
     %datasets = {{{'YALE_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL'}, fwavelet, type}, ...
      %           {{'YALE_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LH'}, fwavelet, type}, ...
       %          {{'YALE_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:HL'}, fwavelet, type}, ...
        %         {{'YALE_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL+HL'}, fwavelet, type}, ...
        %         {{'YALE_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL+HL+LH'}, fwavelet, type}, ...
         %        {{'AR_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL'}, fwavelet, type}, ...
          %       {{'AR_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LH'}, fwavelet, type}, ...
           %      {{'AR_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:HL'}, fwavelet, type}, ...
            %     {{'AR_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL+HL'}, fwavelet, type}, ...
             %    {{'AR_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL+HL+LH'}, fwavelet, type}, ...
              %   {{'SDUMLA_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL'}, fwavelet, type}, ...
               %  {{'SDUMLA_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LH'}, fwavelet, type}, ...
                % {{'SDUMLA_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:HL'}, fwavelet, type}, ...
                 %{{'SDUMLA_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL+HL'}, fwavelet, type}, ...
                 %{{'SDUMLA_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL+HL+LH'}, fwavelet, type}};
            
    
    datasets = {{{'JAFFE_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL'}, fwavelet, type}, ...
                 {{'JAFFE_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LH'}, fwavelet, type}, ...
                 {{'JAFFE_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:HL'}, fwavelet, type}, ...
                 {{'JAFFE_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL+HL'}, fwavelet, type}, ...
                 {{'JAFFE_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL+HL+LH'}, fwavelet, type}};
             
    for dts = 1:size(datasets, 2)
        
        for cmp = 1:size(components, 2)
            dataset = datasets{dts}{1};
            parameters = datasets{dts}{2};
            param = datasets{dts}{3};
            k_fold_3(dataset, parameters, size(components{cmp}, 2), components{cmp}, param);
        end
    end
end

