function main()
    
    k = [1, 3, 5, 8, 10];
    fwavelet = {'db2', 'db4', 'sym3', 'sym4', 'sym5'};
    type = 'wavelet';
    
    %datasets = {{{'YALE_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL'}, fwavelet, k, type}, ...
     %           {{'YALE_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LH'}, fwavelet, k, type}, ...
      %          {{'YALE_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:HL'}, fwavelet, k, type}, ...
       %         {{'YALE_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL+HL'}, fwavelet, k, type}, ...
        %        {{'YALE_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL+HL+LH'}, fwavelet, k, type}, ...
         %       {{'AR_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL'}, fwavelet, k, type}, ...
          %      {{'AR_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LH'}, fwavelet, k, type}, ...
           %     {{'AR_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:HL'}, fwavelet, k, type}, ...
            %    {{'AR_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL+HL'}, fwavelet, k, type}, ...
             %   {{'AR_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL+HL+LH'}, fwavelet, k, type}, ...
              %  {{'SDUMLA_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL'}, fwavelet, k, type}, ...
               % {{'SDUMLA_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LH'}, fwavelet, k, type}, ...
                %{{'SDUMLA_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:HL'}, fwavelet, k, type}, ...
                %{{'SDUMLA_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL+HL'}, fwavelet, k, type}, ...
                %{{'SDUMLA_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL+HL+LH'}, fwavelet, k, type},...
                %{{'JAFFE_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL'}, fwavelet, k, type}, ...
                %{{'JAFFE_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LH'}, fwavelet, k, type}, ...
                %{{'JAFFE_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:HL'}, fwavelet, k, type}, ...
                %{{'JAFFE_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL+HL'}, fwavelet, k, type}, ...
                %{{'JAFFE_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL+HL+LH'}, fwavelet, k, type}};
     
     datasets = {{{'ORL_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL'}, fwavelet, k, type}, ...
                {{'ORL_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LH'}, fwavelet, k, type}, ...
                {{'ORL_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:HL'}, fwavelet, k, type}, ...
                {{'ORL_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL+HL'}, fwavelet, k, type}, ...
                {{'ORL_Viola_Jones-WAVELET-TRANSFORM-LEVEL:3-COMBINATION:LL+HL+LH'}, fwavelet, k, type}};
    for dts = 1:size(datasets, 2)
        
        dataset = datasets{dts}{1};
        parameters = datasets{dts}{2};
        k = datasets{dts}{3};
        param = datasets{dts}{4};
        
        k_fold_3(dataset, parameters, k, param);
        
    end
    
    processing_table_results();
end

